server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: proxy
  cloud:
    gateway:
      routes:
        - id: get
          uri: https://petstore.swagger.io/
          predicates:
            - Path=/pet/available
            - Method=GET
          filters:
            - RewritePath=/pet/available, /v2/pet/findByStatus?status=available
        - id: post
          uri: https://petstore.swagger.io/
          predicates:
            - Path=/pet/create
            - Method=POST
          filters:
            - RewritePath=/pet/create, /v2/pet
            - name: PreFilter
              args:
                name: hellow

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_hD0lybVf1
          jwk-set-uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_hD0lybVf1/.well-known/jwks.json

  main:
    web-application-type: reactive

logging:
  level:
    be.rnb.test: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG